version: 0.0
os: linux
files:
  - source: /
    destination: /opt/src/sample_app
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu
  BeforeInstall:
    - location: scripts/compile.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu